### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by allahbaksh** [msintuneappsdk/Taskr-Sample-Intune-Android-App#1]
When tried building it from the source the following error is reported.

Unexpected scopes found in folder '/workspaces/shamsworkspace/Taskr-Sample-Intune-Android-App-master/app/build/intermediates/transforms/MamifyTransform/debug'. Required: SUB_PROJECTS. Found: PROJECT, SUB_PROJECTS

**Comment by bannus** [comment]
Does this still occur if you delete everything under `app/build` and rebuild? That error suggests you have stale build artifacts.

**Comment by bannus** [comment]
You may also want to try disabling Instant Run.

**Comment by exxoff** [comment]
I had the same problem, disabling Instant Run fixed it for me.

**Comment by meghandaly** [comment]
Disabling Instant Run will resolve this issue. 

@allahbaksh If the error persists please reopen the issue.
