### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [msintuneappsdk/Taskr-Sample-Intune-Android-App#2]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by msintuneappsdk** [comment]
Hi @mansya, thank you for your comment. Our sample app is all set with an icon at this time. Best of luck!
