### ISSUE TITLE
Is this sample app available to test app protection policy?

### ISSUE THREAD

**Issue by niechaoqun9456** [msintuneappsdk/Taskr-Sample-Intune-Android-App#29]
I config the sample with my own auth_config and able to log in with MSAL. Then I create a app protection policy for this app in admin console, but the policy is not applied. My question: Is this sample app available to test app protection policy? Or I need to set up other code to test app protection policy with this sample app. Thanks in advance.

**Comment by codylund** [comment]
@niechaoqun9456 Yes, it should be possible to test app protection policy (APP) against this app. You will need to complete all the changes as discussed [here](https://github.com/msintuneappsdk/Taskr-Sample-Intune-Android-App#important-notes-before-starting). Assuming you complete all of those steps correctly, the app should be compatible with APP with no additional code changes.

Apart from the required configuration to support the sample, there are many reasons why policy is not being applied. If you continue to encounter issues, please share specific repro steps and logs to help us investigate.

**Comment by niechaoqun9456** [comment]
Finally got my policy applied, thanks for your reply.
