### ISSUE TITLE
Demo App Stuck at "Install Company Portal app" dialog

### ISSUE THREAD

**Issue by AbhijitParate** [msintuneappsdk/Taskr-Sample-Intune-Android-App#3]
Trying out Demo app for MAM. 
1. Created app in Intune portal
2. Added permissions and ran the app
3. Signed in with assigned user
4. sign successful
5. Shows prompt to install Company Portal

Stuck forever at screen 5, ever after app restart, device restart.

Also tried clearing app data while company portal is still installed and then logging in the demo app. It still shows the dialog from step 5.

I upgraded the libraries to latest version -> 5.7.1

![image](https://user-images.githubusercontent.com/10205652/61853305-37dedf00-aed9-11e9-9950-4beef2a8b777.png)

**Comment by AbhijitParate** [comment]
@meghandaly Can you please direct me to someone who can help with this?

**Comment by meghandaly** [comment]
Hi @AbhijitParate, 

Can you trying adding `android.injected.testOnly=false` to the [project's 
gradle properties file](https://github.com/msintuneappsdk/Taskr-Sample-Intune-Android-App/blob/master/gradle.properties)?

This should force the application to recognize the Company Portal.

**Comment by AbhijitParate** [comment]
Hey @meghandaly , That worked. Thanks a lot.

I noticed handing over to Company Portal is not very smooth. I had to login multiple times. While I was entering email and password another login prompt appeared. Several of them. I guess due auto-retry mechanism.

**Comment by meghandaly** [comment]
@AbhijitParate Of course, happy to hear that resolved the issue for you. 

Thank you for that observation. I will investigate further and see what improvements can be made.
