### ISSUE TITLE
chromeimu source code integration Intune

### ISSUE THREAD

**Issue by yaxin3690** [msintuneappsdk/Taskr-Sample-Intune-Android-App#32]
We use chromeimu source code to compile and generate secure browser. Now when we need to connect with Intune-sdk, we find that SDK cannot be integrated into the browser source code. For this problem, do you have any way to deal with it for my reference?

**Comment by bannus** [comment]
For integration issues, can you create a ticket for the main Intune SDK project and fully complete the issue template?

https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues
