### ISSUE TITLE
android:exported needs to be explicitly specified for element <receiver#com.microsoft.intune.mam.client.service.MAMBackgroundReceiver>

### ISSUE THREAD

**Issue by DpatilVOIS** [msintuneappsdk/Taskr-Sample-Intune-Android-App#36]
I am using below version in build.gradle
       buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 31
        targetSdkVersion = 31

And I got the below issue.

Manifest merger failed : android:exported needs to be explicitly specified for element <receiver#com.microsoft.intune.mam.client.service.MAMBackgroundReceiver>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

**Comment by bannus** [comment]
This repo is for the Taskr sample app. Please create a new issue at https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues, and fill out the full issue template. For this issue in particular, please make sure you are using the latest version of the Intune App SDK.
