### ISSUE TITLE
Difference in App Un-enrollment behavior in iOS and Android 

### ISSUE THREAD

**Issue by AbhijitParate** [msintuneappsdk/Taskr-Sample-Intune-Android-App#4]
When un-enrolling the app by calling
```
MAMEnrollmentManager::unregisterAccountForMAM(String upn)
```
in iOS, method accepts additional flag 'withWipe' but in Android app's data gets wiped forcefully.

Is there any way we can get similar behavior as iOS? 
We don't really want to wipe the app's data in Android.

**Comment by meghandaly** [comment]
@AbhijitParate Please see the section for [registering for notifications from the SDK](https://docs.microsoft.com/en-us/intune/developer/app-sdk-android#register-for-notifications-from-the-sdk) in our public documentation specifically the section regarding the `WIPE_USER_DATA` notification.

It is worth noting that the expectation on unenrollment is that app data associated with the managed account in a single identity app would be removed upon unenrollment.
