### ISSUE TITLE
AADSTS90013: Invalid input received from the user.

### ISSUE THREAD

**Issue by Sicmatr1x** [msintuneappsdk/Taskr-Sample-Intune-Android-App#6]
I clone the demo and run it in Android Studio

![image](https://user-images.githubusercontent.com/26240752/72587027-c5eace00-392e-11ea-8354-10ecf00e2f42.png)

```
E/AcquireTokenRequest:tryAcquireTokenSilent:  [2020-01-17 05:35:49 - 86c80666-13f5-42e3-8854-28cd173c2eed] AUTH_REFRESH_FAILED_PROMPT_NOT_ALLOWED:Prompt is not allowed and failed to get token. No result returned from acquireTokenSilent ver:1.16.3 Android 28
```

**Comment by meghandaly** [comment]
@Sicmatr1x You need to follow the steps outlined in the [`README`and change the relevant AAD values](https://github.com/msintuneappsdk/Taskr-Sample-Intune-Android-App#configuring-app-for-adal-authentication). 

When those values are not changed the app will not be able to access AAD and will interpret the values in the `AuthManager` as invalid input.
