### ISSUE TITLE
Code is not building in Android studio

### ISSUE THREAD

**Issue by mohit1993** [msintuneappsdk/Taskr-Sample-Intune-Android-App#9]
Getting this error while build apk:

C:\Users\Administrator\InTune\Taskr-Sample-Intune-Android-App\app\src\main\java\com\microsoft\intune\samples\taskr\authentication\AuthManager.java:18: error: cannot find symbol
import com.microsoft.aad.adal.AuthenticationCallback;
                             ^
  symbol:   class AuthenticationCallback
  location: package com.microsoft.aad.adal

**Comment by meghandaly** [comment]
@mohit1993 Thank you for bringing this to our attention. ADAL authentication files that should have been removed were missed in the 2.0 update. This has been corrected.
